export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_PRODCUTO = 'SELECCIONAR_PRODCUTO';
export const CANTIDAD_PRODCUTOS = 'CANTIDAD_PRODCUTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';
